# Generated by Django 5.1.14 on 2026-08-15 02:26

import apps.accounts.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('owner', 'İşletme sahibi'), ('general_manager', 'Genel müdür'), ('restaurant_manager', 'Restoran müdürü'), ('chef', 'Şef'), ('kitchen_staff', 'Mutfak personeli'), ('head_waiter', 'Şef garson'), ('waiter', 'Garson'), ('cashier', 'Kasiyer'), ('bartender', 'Bar personeli'), ('storekeeper', 'Depo / satın alma'), ('accountant', 'Muhasebe'), ('courier', 'Kurye')], db_index=True, default='waiter', max_length=32, verbose_name='rol')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Geçerli bir telefon numarası girin.', regex='^[0-9+()\\s\\-]{7,20}$')], verbose_name='telefon')),
                ('employee_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='personel kodu')),
                ('pin_hash', models.CharField(blank=True, editable=False, max_length=128, verbose_name='PIN (hash)')),
                ('extra_permissions', models.JSONField(blank=True, default=list, help_text='Rolün ötesinde verilen izin kodları.', verbose_name='ek izinler')),
                ('denied_permissions', models.JSONField(blank=True, default=list, help_text='Rolde bulunsa bile bu kullanıcıya kapatılan izin kodları.', verbose_name='reddedilen izinler')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='profil görseli')),
                ('theme_preference', models.CharField(choices=[('auto', 'Sistem'), ('light', 'Açık'), ('dark', 'Koyu')], default='auto', max_length=10, verbose_name='tema')),
                ('language_preference', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', max_length=5, verbose_name='dil')),
                ('must_change_password', models.BooleanField(default=False, help_text='İlk girişte parola değiştirmeye zorlar.', verbose_name='parola değiştirmeli')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='parola değişim zamanı')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='son etkinlik')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ['first_name', 'last_name', 'username'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ManagerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=64, verbose_name='izin kodu')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='gerekçe')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='nesne türü')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='nesne kimliği')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='zaman')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_given', to=settings.AUTH_USER_MODEL, verbose_name='onaylayan')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_requested', to=settings.AUTH_USER_MODEL, verbose_name='talep eden')),
            ],
            options={
                'verbose_name': 'Yetkili onayı',
                'verbose_name_plural': 'Yetkili onayları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
    ]
