# Generated by Django 5.2.16 on 2026-08-15 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('filename', models.CharField(max_length=200, unique=True, verbose_name='dosya adı')),
                ('kind', models.CharField(choices=[('manual', 'Elle'), ('scheduled', 'Otomatik'), ('pre_restore', 'Geri yükleme öncesi güvenlik')], db_index=True, default='manual', max_length=16, verbose_name='tür')),
                ('status', models.CharField(choices=[('running', 'Sürüyor'), ('success', 'Başarılı'), ('failed', 'Başarısız')], db_index=True, default='running', max_length=10, verbose_name='durum')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='boyut (bayt)')),
                ('checksum', models.CharField(blank=True, help_text='Dosyanın bozulmadığını doğrulamak için.', max_length=64, verbose_name='SHA-256')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='bitiş')),
                ('contents', models.JSONField(blank=True, default=dict, verbose_name='içerik')),
                ('includes_secrets', models.BooleanField(default=False, help_text='.env dosyası (API anahtarları) yedeğe eklendiyse işaretlidir.', verbose_name='gizli ayarlar dahil')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='not')),
                ('error_message', models.TextField(blank=True, verbose_name='hata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Yedek',
                'verbose_name_plural': 'Yedekler',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('source_filename', models.CharField(max_length=200, verbose_name='kaynak yedek')),
                ('status', models.CharField(choices=[('success', 'Başarılı'), ('failed', 'Başarısız')], max_length=10, verbose_name='durum')),
                ('error_message', models.TextField(blank=True, verbose_name='hata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('safety_backup', models.ForeignKey(blank=True, help_text='Geri yüklemeden hemen önce alınan yedek.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores_protected', to='backups.backuprecord', verbose_name='güvenlik yedeği')),
            ],
            options={
                'verbose_name': 'Geri yükleme',
                'verbose_name_plural': 'Geri yüklemeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['-started_at', 'status'], name='backups_bac_started_79701b_idx'),
        ),
    ]
