# Generated by Django 5.2.16 on 2026-08-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorerecord',
            name='performed_by_username',
            field=models.CharField(blank=True, help_text='Geri yükleme sonrası kullanıcı kaydı yedekteki hâline döner; işlemi kimin yaptığı burada metin olarak korunur.', max_length=150, verbose_name='işlemi yapan'),
        ),
    ]
