# Generated by Django 5.2.16 on 2026-08-15 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_key', models.CharField(db_index=True, max_length=60, verbose_name='ders')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='tamamlanma')),
                ('quiz_correct', models.PositiveSmallIntegerField(default=0, verbose_name='doğru yanıt')),
                ('quiz_total', models.PositiveSmallIntegerField(default=0, verbose_name='soru sayısı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
            options={
                'verbose_name': 'Ders ilerlemesi',
                'verbose_name_plural': 'Ders ilerlemeleri',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson_key'), name='uniq_lesson_per_user')],
            },
        ),
    ]
