# Generated by Django 5.1.14 on 2026-08-15 02:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='ad')),
                ('code', models.SlugField(blank=True, max_length=40, unique=True, verbose_name='kod')),
                ('kind', models.CharField(choices=[('kitchen', 'Mutfak'), ('grill', 'Izgara'), ('cold', 'Soğuk mutfak'), ('bar', 'Bar'), ('dessert', 'Tatlı'), ('pastry', 'Pastane')], default='kitchen', max_length=10, verbose_name='tür')),
                ('color', models.CharField(default='#fd7e14', max_length=7, verbose_name='renk')),
                ('printer_name', models.CharField(blank=True, help_text='KOT çıktısının gönderileceği yazıcı (isteğe bağlı).', max_length=100, verbose_name='yazıcı adı')),
                ('warning_minutes', models.PositiveIntegerField(default=10, help_text='Bu süreyi aşan siparişler sarı renkte gösterilir.', verbose_name='uyarı süresi (dk)')),
                ('critical_minutes', models.PositiveIntegerField(default=20, help_text='Bu süreyi aşan siparişler kırmızı renkte ve sesli uyarıyla gösterilir.', verbose_name='kritik süre (dk)')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'İstasyon',
                'verbose_name_plural': 'İstasyonlar',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('preparing', 'Hazırlanıyor'), ('ready', 'Hazır'), ('cancelled', 'İptal')], default='pending', max_length=10, verbose_name='durum')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='tamamlanma')),
            ],
            options={
                'verbose_name': 'KOT satırı',
                'verbose_name_plural': 'KOT satırları',
            },
        ),
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='KOT no')),
                ('status', models.CharField(choices=[('queued', 'Sırada'), ('preparing', 'Hazırlanıyor'), ('ready', 'Hazır'), ('completed', 'Teslim edildi'), ('cancelled', 'İptal')], db_index=True, default='queued', max_length=10, verbose_name='durum')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Düşük'), (2, 'Normal'), (3, 'Yüksek'), (4, 'Acil')], default=2, verbose_name='öncelik')),
                ('course', models.PositiveSmallIntegerField(default=1, verbose_name='servis sırası')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='not')),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='sıraya girme')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='başlama')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='hazır olma')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='teslim')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='yazdırma zamanı')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='tamamlayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Mutfak fişi (KOT)',
                'verbose_name_plural': 'Mutfak fişleri (KOT)',
                'ordering': ['-priority', 'queued_at'],
            },
        ),
    ]
