# Generated by Django 5.1.14 on 2026-08-15 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchen', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.order', verbose_name='sipariş'),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_tickets', to=settings.AUTH_USER_MODEL, verbose_name='başlatan'),
        ),
        migrations.AddField(
            model_name='station',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='kitchen.station', verbose_name='istasyon'),
        ),
        migrations.AddField(
            model_name='ticketline',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_lines', to='orders.orderitem', verbose_name='sipariş satırı'),
        ),
        migrations.AddField(
            model_name='ticketline',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kitchen.kitchenticket', verbose_name='KOT'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['station', 'status', 'queued_at'], name='kitchen_kit_station_31cfed_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['status', '-priority'], name='kitchen_kit_status_a86185_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketline',
            constraint=models.UniqueConstraint(fields=('ticket', 'order_item'), name='uniq_order_item_per_ticket'),
        ),
    ]
