# Generated by Django 5.1.14 on 2026-08-15 02:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='anahtar')),
                ('label', models.CharField(max_length=200, verbose_name='etiket')),
                ('value', models.TextField(blank=True, verbose_name='değer')),
                ('value_type', models.CharField(choices=[('string', 'Metin'), ('integer', 'Tam sayı'), ('decimal', 'Ondalık'), ('boolean', 'Evet/Hayır'), ('json', 'JSON')], default='string', max_length=10, verbose_name='tür')),
                ('group', models.CharField(db_index=True, default='genel', max_length=50, verbose_name='grup')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('is_editable', models.BooleanField(default=True, verbose_name='düzenlenebilir')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Sistem ayarı',
                'verbose_name_plural': 'Sistem ayarları',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='zaman')),
                ('username_snapshot', models.CharField(blank=True, help_text='Kullanıcı silinse bile iz kaybolmaz.', max_length=150, verbose_name='kullanıcı adı (anlık)')),
                ('action', models.CharField(choices=[('create', 'Oluşturma'), ('update', 'Güncelleme'), ('delete', 'Silme'), ('login', 'Giriş'), ('login_failed', 'Başarısız giriş'), ('logout', 'Çıkış'), ('void', 'İptal'), ('refund', 'İade'), ('discount', 'İndirim'), ('permission', 'Yetki değişikliği'), ('export', 'Dışa aktarma'), ('ai_call', 'AI çağrısı'), ('terminal', 'Terminal komutu'), ('code_apply', 'Kod değişikliği uygulama'), ('cash', 'Kasa işlemi'), ('data_erasure', 'Veri silme talebi (KVKK)')], db_index=True, max_length=24, verbose_name='işlem')),
                ('severity', models.CharField(choices=[('info', 'Bilgi'), ('notice', 'Dikkat'), ('warning', 'Uyarı'), ('critical', 'Kritik')], db_index=True, default='info', max_length=10, verbose_name='önem')),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='nesne türü')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='nesne kimliği')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='değişiklikler')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresi')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='tarayıcı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
            options={
                'verbose_name': 'Denetim kaydı',
                'verbose_name_plural': 'Denetim kayıtları',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'action'], name='core_auditl_timesta_cded18_idx'), models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='Belirli rollere yayın yapmak için rol kodları listesi.', verbose_name='hedef roller')),
                ('level', models.CharField(choices=[('info', 'Bilgi'), ('success', 'Başarılı'), ('warning', 'Uyarı'), ('danger', 'Kritik')], default='info', max_length=10, verbose_name='düzey')),
                ('category', models.CharField(choices=[('stock', 'Stok'), ('order', 'Sipariş'), ('kitchen', 'Mutfak'), ('reservation', 'Rezervasyon'), ('finance', 'Finans'), ('ai', 'Yapay zekâ'), ('security', 'Güvenlik'), ('system', 'Sistem')], db_index=True, default='system', max_length=20, verbose_name='kategori')),
                ('title', models.CharField(max_length=200, verbose_name='başlık')),
                ('body', models.TextField(blank=True, verbose_name='içerik')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='bağlantı')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='okundu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='okunma zamanı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('recipient', models.ForeignKey(blank=True, help_text='Boş ise yetkili tüm kullanıcılara gösterilir.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='alıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='core_notifi_recipie_1d5476_idx')],
            },
        ),
    ]
