# Generated by Django 5.1.14 on 2026-08-15 02:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ad')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='sıra')),
            ],
            options={
                'verbose_name': 'Malzeme kategorisi',
                'verbose_name_plural': 'Malzeme kategorileri',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='kod')),
                ('name', models.CharField(max_length=60, verbose_name='ad')),
                ('dimension', models.CharField(choices=[('mass', 'Ağırlık'), ('volume', 'Hacim'), ('count', 'Adet')], default='mass', max_length=10, verbose_name='boyut')),
                ('factor_to_base', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='1 bu birim = kaç temel birim? (ör. kg -> 1000 g)', max_digits=16, verbose_name='temel birime katsayı')),
                ('is_base', models.BooleanField(default=False, verbose_name='temel birim')),
            ],
            options={
                'verbose_name': 'Ölçü birimi',
                'verbose_name_plural': 'Ölçü birimleri',
                'ordering': ['dimension', '-is_base', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(db_index=True, max_length=160, verbose_name='ad')),
                ('sku', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='stok kodu')),
                ('critical_level', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Bu seviyenin altına düşünce uyarı üretilir (temel birimde).', max_digits=14, verbose_name='kritik seviye')),
                ('reorder_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='sipariş miktarı')),
                ('is_perishable', models.BooleanField(default=False, verbose_name='bozulabilir')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='raf ömrü (gün)')),
                ('rotation', models.CharField(choices=[('fifo', 'FIFO - İlk giren ilk çıkar'), ('fefo', 'FEFO - Önce son kullanma tarihi yakın olan')], default='fefo', max_length=4, verbose_name='tüketim yöntemi')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktif')),
                ('notes', models.TextField(blank=True, verbose_name='notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='inventory.ingredientcategory', verbose_name='kategori')),
            ],
            options={
                'verbose_name': 'Malzeme',
                'verbose_name_plural': 'Malzemeler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ad')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='yetkili')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('address', models.TextField(blank=True, verbose_name='adres')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='vergi no')),
                ('payment_terms_days', models.PositiveIntegerField(default=0, verbose_name='vade (gün)')),
                ('lead_time_days', models.PositiveIntegerField(default=1, verbose_name='teslim süresi (gün)')),
                ('rating', models.PositiveSmallIntegerField(default=3, help_text='1-5 arası', verbose_name='değerlendirme')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('notes', models.TextField(blank=True, verbose_name='notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('lot_code', models.CharField(blank=True, max_length=60, verbose_name='parti kodu')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='giriş miktarı')),
                ('remaining_quantity', models.DecimalField(db_index=True, decimal_places=3, max_digits=16, verbose_name='kalan miktar')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Temel birim başına maliyet.', max_digits=14, verbose_name='birim maliyet')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='giriş zamanı')),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='son kullanma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.ingredient', verbose_name='malzeme')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.supplier', verbose_name='tedarikçi')),
            ],
            options={
                'verbose_name': 'Stok partisi',
                'verbose_name_plural': 'Stok partileri',
                'ordering': ['expiry_date', 'received_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='belge no')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('requested', 'Talep edildi'), ('approved', 'Onaylandı'), ('ordered', 'Sipariş verildi'), ('partial', 'Kısmi teslim'), ('received', 'Teslim alındı'), ('cancelled', 'İptal')], db_index=True, default='draft', max_length=12, verbose_name='durum')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='beklenen teslim')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='teslim zamanı')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='onay zamanı')),
                ('invoice_number', models.CharField(blank=True, max_length=60, verbose_name='fatura no')),
                ('notes', models.TextField(blank=True, verbose_name='notlar')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='onaylayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier', verbose_name='tedarikçi')),
            ],
            options={
                'verbose_name': 'Satın alma siparişi',
                'verbose_name_plural': 'Satın alma siparişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_ingredients', to='inventory.supplier', verbose_name='varsayılan tedarikçi'),
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='birim fiyat')),
                ('minimum_order_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='asgari sipariş')),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='geçerlilik başlangıcı')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='inventory.ingredient', verbose_name='malzeme')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='inventory.supplier', verbose_name='tedarikçi')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='birim')),
            ],
            options={
                'verbose_name': 'Tedarikçi fiyatı',
                'verbose_name_plural': 'Tedarikçi fiyatları',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='miktar')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='teslim alınan')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='birim fiyat')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='KDV (%)')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='son kullanma')),
                ('lot_code', models.CharField(blank=True, max_length=60, verbose_name='parti kodu')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.ingredient', verbose_name='malzeme')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder', verbose_name='sipariş')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='birim')),
            ],
            options={
                'verbose_name': 'Satın alma satırı',
                'verbose_name_plural': 'Satın alma satırları',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='base_unit',
            field=models.ForeignKey(help_text='Stok bu birimde tutulur (ör. gram, ml, adet).', on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='inventory.unitofmeasure', verbose_name='temel birim'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, help_text='Tedarikçiden alınan birim (ör. kg, koli).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_ingredients', to='inventory.unitofmeasure', verbose_name='satın alma birimi'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ad')),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='kod')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='konum')),
                ('is_default', models.BooleanField(default=False, verbose_name='varsayılan')),
                ('is_cold_storage', models.BooleanField(default=False, verbose_name='soğuk depo')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Depo',
                'verbose_name_plural': 'Depolar',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('movement_type', models.CharField(choices=[('purchase', 'Satın alma girişi'), ('sale', 'Satış (reçete düşümü)'), ('waste', 'Fire / israf'), ('adjustment', 'Sayım düzeltmesi'), ('transfer_in', 'Depo transferi (giriş)'), ('transfer_out', 'Depo transferi (çıkış)'), ('return', 'Tedarikçiye iade'), ('production', 'Üretim tüketimi'), ('void_restock', 'İptal / iade geri yükleme'), ('opening', 'Açılış stoğu')], db_index=True, max_length=16, verbose_name='hareket türü')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Temel birimde. Çıkışlar negatiftir.', max_digits=16, verbose_name='miktar')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='birim maliyet')),
                ('balance_after', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, verbose_name='işlem sonrası bakiye')),
                ('reference_type', models.CharField(blank=True, max_length=60, verbose_name='kaynak türü')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='kaynak kimliği')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='not')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stockbatch', verbose_name='parti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.ingredient', verbose_name='malzeme')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse', verbose_name='depo')),
            ],
            options={
                'verbose_name': 'Stok hareketi',
                'verbose_name_plural': 'Stok hareketleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, verbose_name='miktar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.ingredient', verbose_name='malzeme')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse', verbose_name='depo')),
            ],
            options={
                'verbose_name': 'Depo stoğu',
                'verbose_name_plural': 'Depo stokları',
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='sayım no')),
                ('status', models.CharField(choices=[('open', 'Devam ediyor'), ('applied', 'Uygulandı'), ('cancelled', 'İptal')], default='open', max_length=10, verbose_name='durum')),
                ('counted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sayım zamanı')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='uygulanma zamanı')),
                ('notes', models.TextField(blank=True, verbose_name='notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='inventory.warehouse', verbose_name='depo')),
            ],
            options={
                'verbose_name': 'Stok sayımı',
                'verbose_name_plural': 'Stok sayımları',
                'ordering': ['-counted_at'],
            },
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.warehouse', verbose_name='depo'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouse', verbose_name='teslim deposu'),
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='miktar')),
                ('reason', models.CharField(choices=[('expired', 'Son kullanma tarihi geçti'), ('spoiled', 'Bozulma'), ('broken', 'Kırılma / dökülme'), ('prep_error', 'Hazırlık hatası'), ('customer_return', 'Müşteri iadesi'), ('overproduction', 'Fazla üretim'), ('theft', 'Kayıp / hırsızlık şüphesi'), ('other', 'Diğer')], max_length=20, verbose_name='neden')),
                ('cost_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='maliyet tutarı')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='oluşma zamanı')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='inventory.ingredient', verbose_name='malzeme')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_reports', to=settings.AUTH_USER_MODEL, verbose_name='bildiren')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='inventory.warehouse', verbose_name='depo')),
            ],
            options={
                'verbose_name': 'Fire kaydı',
                'verbose_name_plural': 'Fire kayıtları',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, verbose_name='sistem miktarı')),
                ('counted_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, verbose_name='sayılan miktar')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='not')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount', verbose_name='sayım')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='inventory.ingredient', verbose_name='malzeme')),
            ],
            options={
                'verbose_name': 'Sayım satırı',
                'verbose_name_plural': 'Sayım satırları',
                'constraints': [models.UniqueConstraint(fields=('count', 'ingredient'), name='uniq_ingredient_per_count')],
            },
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['is_active', 'name'], name='inventory_i_is_acti_995d02_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['ingredient', '-created_at'], name='inventory_s_ingredi_ddeb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_5aaa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['warehouse', 'ingredient'], name='inventory_s_warehou_5501b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('ingredient', 'warehouse'), name='uniq_stock_per_warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['ingredient', 'warehouse', 'remaining_quantity'], name='inventory_s_ingredi_7cff50_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='inventory_s_expiry__709598_idx'),
        ),
        migrations.AddIndex(
            model_name='wasterecord',
            index=models.Index(fields=['-occurred_at', 'reason'], name='inventory_w_occurre_31084a_idx'),
        ),
    ]
