# Generated by Django 5.1.14 on 2026-08-15 02:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ad')),
                ('code', models.SlugField(blank=True, max_length=40, unique=True, verbose_name='kod')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('is_outdoor', models.BooleanField(default=False, verbose_name='açık alan')),
                ('is_smoking', models.BooleanField(default=False, verbose_name='sigara içilebilir')),
                ('service_charge_rate', models.DecimalField(decimal_places=2, default=0, help_text='Bu bölümdeki siparişlere eklenecek servis oranı.', max_digits=5, verbose_name='servis bedeli (%)')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Salon / Bölüm',
                'verbose_name_plural': 'Salonlar / Bölümler',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=40, verbose_name='masa adı')),
                ('capacity', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='kapasite')),
                ('status', models.CharField(choices=[('free', 'Boş'), ('occupied', 'Dolu'), ('reserved', 'Rezerve'), ('cleaning', 'Temizlikte'), ('disabled', 'Kullanım dışı')], db_index=True, default='free', max_length=10, verbose_name='durum')),
                ('shape', models.CharField(choices=[('square', 'Kare'), ('round', 'Yuvarlak'), ('rect', 'Dikdörtgen')], default='square', max_length=10, verbose_name='şekil')),
                ('pos_x', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='X konumu (%)')),
                ('pos_y', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Y konumu (%)')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR anahtarı')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='not')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktif')),
                ('occupied_since', models.DateTimeField(blank=True, null=True, verbose_name='doluluk başlangıcı')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='floor.area', verbose_name='bölüm')),
                ('assigned_waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to=settings.AUTH_USER_MODEL, verbose_name='atanan garson')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Masa birleştirildiğinde ana masayı gösterir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_tables', to='floor.table', verbose_name='birleştirildiği masa')),
            ],
            options={
                'verbose_name': 'Masa',
                'verbose_name_plural': 'Masalar',
                'ordering': ['area__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='rezervasyon kodu')),
                ('guest_name', models.CharField(max_length=120, verbose_name='misafir adı')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('party_size', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='kişi sayısı')),
                ('reserved_at', models.DateTimeField(db_index=True, verbose_name='rezervasyon zamanı')),
                ('duration_minutes', models.PositiveIntegerField(default=90, verbose_name='süre (dk)')),
                ('status', models.CharField(choices=[('pending', 'Onay bekliyor'), ('confirmed', 'Onaylandı'), ('seated', 'Misafir oturdu'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal edildi'), ('no_show', 'Gelmedi')], db_index=True, default='confirmed', max_length=10, verbose_name='durum')),
                ('source', models.CharField(choices=[('phone', 'Telefon'), ('walk_in', 'Kapıdan'), ('online', 'Online'), ('partner', 'Anlaşmalı platform')], default='phone', max_length=10, verbose_name='kaynak')),
                ('special_requests', models.TextField(blank=True, verbose_name='özel istekler')),
                ('allergy_notes', models.CharField(blank=True, max_length=300, verbose_name='alerji notu')),
                ('occasion', models.CharField(blank=True, help_text='Doğum günü, yıldönümü vb.', max_length=60, verbose_name='özel gün')),
                ('seated_at', models.DateTimeField(blank=True, null=True, verbose_name='oturma zamanı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='bitiş zamanı')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='hatırlatma gönderildi')),
                ('cancellation_reason', models.CharField(blank=True, max_length=300, verbose_name='iptal nedeni')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='floor.area', verbose_name='tercih edilen bölüm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='crm.customer', verbose_name='müşteri')),
                ('tables', models.ManyToManyField(blank=True, related_name='reservations', to='floor.table', verbose_name='masalar')),
            ],
            options={
                'verbose_name': 'Rezervasyon',
                'verbose_name_plural': 'Rezervasyonlar',
                'ordering': ['reserved_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('guest_name', models.CharField(max_length=120, verbose_name='misafir adı')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('party_size', models.PositiveSmallIntegerField(default=2, verbose_name='kişi sayısı')),
                ('status', models.CharField(choices=[('waiting', 'Bekliyor'), ('notified', 'Çağrıldı'), ('seated', 'Oturdu'), ('left', 'Ayrıldı')], db_index=True, default='waiting', max_length=10, verbose_name='durum')),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=15, verbose_name='tahminî bekleme (dk)')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='çağrılma zamanı')),
                ('seated_at', models.DateTimeField(blank=True, null=True, verbose_name='oturma zamanı')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='not')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='floor.area', verbose_name='tercih')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Bekleme listesi kaydı',
                'verbose_name_plural': 'Bekleme listesi',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['status', 'is_active'], name='floor_table_status_e8f3b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('area', 'name'), name='uniq_table_name_per_area'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reserved_at', 'status'], name='floor_reser_reserve_65cf1c_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['guest_phone'], name='floor_reser_guest_p_4853ac_idx'),
        ),
    ]
