# Generated by Django 5.1.14 on 2026-08-15 02:26

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=200, verbose_name='ad')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('active', 'Aktif'), ('paused', 'Duraklatıldı'), ('finished', 'Bitti')], default='draft', max_length=10, verbose_name='durum')),
                ('target_segments', models.JSONField(blank=True, default=list, verbose_name='hedef segmentler')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='başlangıç')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='bitiş')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='bütçe')),
                ('is_ai_suggested', models.BooleanField(default=False, help_text='Yapay zekâ tarafından önerilen kampanya.', verbose_name='AI önerisi')),
                ('ai_rationale', models.TextField(blank=True, verbose_name='AI gerekçesi')),
            ],
            options={
                'verbose_name': 'Kampanya',
                'verbose_name_plural': 'Kampanyalar',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('marketing_sms', 'SMS ile pazarlama'), ('marketing_email', 'E-posta ile pazarlama'), ('data_processing', 'Kişisel veri işleme'), ('profiling', 'Profilleme ve öneri')], max_length=20, verbose_name='izin türü')),
                ('granted', models.BooleanField(default=False, verbose_name='verildi')),
                ('source', models.CharField(blank=True, max_length=60, verbose_name='alınma kanalı')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='zaman')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Rıza kaydı',
                'verbose_name_plural': 'Rıza kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='müşteri kodu')),
                ('first_name', models.CharField(max_length=80, verbose_name='ad')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='soyad')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='doğum tarihi')),
                ('address', models.TextField(blank=True, verbose_name='adres')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='firma')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='vergi no')),
                ('segment', models.CharField(choices=[('new', 'Yeni müşteri'), ('regular', 'Düzenli'), ('vip', 'VIP'), ('at_risk', 'Kayıp riski'), ('lost', 'Kayıp'), ('corporate', 'Kurumsal')], db_index=True, default='new', max_length=12, verbose_name='segment')),
                ('tier', models.CharField(choices=[('bronze', 'Bronz'), ('silver', 'Gümüş'), ('gold', 'Altın'), ('platinum', 'Platin')], default='bronze', max_length=10, verbose_name='seviye')),
                ('preferences', models.TextField(blank=True, verbose_name='tercihler')),
                ('allergy_notes', models.CharField(blank=True, help_text='Servis sırasında uyarı olarak gösterilir.', max_length=400, verbose_name='alerji notları')),
                ('internal_notes', models.TextField(blank=True, verbose_name='dahili notlar')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='sadakat puanı')),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='toplam harcama')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='ziyaret sayısı')),
                ('last_visit_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='son ziyaret')),
                ('no_show_count', models.PositiveIntegerField(default=0, verbose_name='gelmediği rezervasyon')),
                ('is_anonymized', models.BooleanField(default=False, verbose_name='anonimleştirildi')),
                ('anonymized_at', models.DateTimeField(blank=True, null=True, verbose_name='anonimleştirme zamanı')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['-last_visit_at', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='kod')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='yüklenen tutar')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='kalan bakiye')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='son kullanma')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'Hediye çeki',
                'verbose_name_plural': 'Hediye çekleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('kind', models.CharField(choices=[('earn', 'Kazanım'), ('redeem', 'Harcama'), ('expire', 'Süre dolumu'), ('adjust', 'Düzeltme'), ('bonus', 'Bonus / kampanya')], max_length=10, verbose_name='tür')),
                ('points', models.IntegerField(help_text='Harcamalar negatiftir.', verbose_name='puan')),
                ('balance_after', models.IntegerField(default=0, verbose_name='işlem sonrası bakiye')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='son kullanma')),
            ],
            options={
                'verbose_name': 'Sadakat hareketi',
                'verbose_name_plural': 'Sadakat hareketleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1-5', verbose_name='puan')),
                ('comment', models.TextField(blank=True, verbose_name='yorum')),
                ('source', models.CharField(choices=[('in_house', 'Restoran içi'), ('qr', 'QR anket'), ('google', 'Google'), ('social', 'Sosyal medya'), ('delivery', 'Teslimat platformu')], default='in_house', max_length=10, verbose_name='kaynak')),
                ('sentiment', models.CharField(choices=[('positive', 'Olumlu'), ('neutral', 'Nötr'), ('negative', 'Olumsuz'), ('unknown', 'Analiz edilmedi')], db_index=True, default='unknown', max_length=10, verbose_name='duygu')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=3, help_text='-1 (çok olumsuz) ile +1 (çok olumlu) arası.', max_digits=4, null=True, verbose_name='duygu skoru')),
                ('topics', models.JSONField(blank=True, default=list, help_text='AI tarafından çıkarılan konu etiketleri (servis, lezzet, fiyat...).', verbose_name='konular')),
                ('ai_summary', models.CharField(blank=True, max_length=300, verbose_name='AI özeti')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='analiz zamanı')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='çözüldü')),
                ('resolution_note', models.TextField(blank=True, verbose_name='çözüm notu')),
            ],
            options={
                'verbose_name': 'Müşteri yorumu',
                'verbose_name_plural': 'Müşteri yorumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
