# Generated by Django 5.1.14 on 2026-08-15 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='orders.coupon', verbose_name='kupon'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='crm.customer', verbose_name='müşteri'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='crm.customer', verbose_name='müşteri'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='crm.customer', verbose_name='müşteri'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order', verbose_name='sipariş'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='crm.customer', verbose_name='müşteri'),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order', verbose_name='sipariş'),
        ),
        migrations.AddField(
            model_name='review',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reviews', to=settings.AUTH_USER_MODEL, verbose_name='çözen'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['segment', '-lifetime_value'], name='crm_custome_segment_47b414_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='crm_custome_phone_eb81ab_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['sentiment', '-created_at'], name='crm_review_sentime_d01a47_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='crm_review_rating_3bae6c_idx'),
        ),
    ]
