# Generated by Django 5.1.14 on 2026-08-15 02:26

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('employment_type', models.CharField(choices=[('full_time', 'Tam zamanlı'), ('part_time', 'Yarı zamanlı'), ('hourly', 'Saatlik'), ('seasonal', 'Sezonluk'), ('intern', 'Stajyer')], default='full_time', max_length=12, verbose_name='çalışma şekli')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='işe giriş')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='işten ayrılış')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='saatlik ücret')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='aylık ücret')),
                ('weekly_hours_target', models.PositiveSmallIntegerField(default=45, verbose_name='haftalık hedef saat')),
                ('emergency_contact', models.CharField(blank=True, max_length=120, verbose_name='acil durum kişisi')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='acil durum telefonu')),
                ('notes', models.TextField(blank=True, verbose_name='notlar')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personel',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('kind', models.CharField(choices=[('annual', 'Yıllık izin'), ('sick', 'Hastalık izni'), ('unpaid', 'Ücretsiz izin'), ('maternity', 'Doğum izni'), ('other', 'Diğer')], default='annual', max_length=10, verbose_name='izin türü')),
                ('start_date', models.DateField(verbose_name='başlangıç')),
                ('end_date', models.DateField(verbose_name='bitiş')),
                ('status', models.CharField(choices=[('pending', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal')], db_index=True, default='pending', max_length=10, verbose_name='durum')),
                ('reason', models.TextField(blank=True, verbose_name='gerekçe')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='karar zamanı')),
                ('decision_note', models.CharField(blank=True, max_length=300, verbose_name='karar notu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_leaves', to=settings.AUTH_USER_MODEL, verbose_name='karar veren')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee', verbose_name='personel')),
            ],
            options={
                'verbose_name': 'İzin talebi',
                'verbose_name_plural': 'İzin talepleri',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='ad')),
                ('start_time', models.TimeField(verbose_name='başlangıç')),
                ('end_time', models.TimeField(verbose_name='bitiş')),
                ('color', models.CharField(default='#6f42c1', max_length=7, verbose_name='renk')),
                ('break_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='mola (dk)')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Vardiya',
                'verbose_name_plural': 'Vardiyalar',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('work_date', models.DateField(db_index=True, verbose_name='tarih')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('confirmed', 'Onaylandı'), ('completed', 'Tamamlandı'), ('absent', 'Gelmedi'), ('swapped', 'Değiştirildi')], default='planned', max_length=10, verbose_name='durum')),
                ('role_note', models.CharField(blank=True, max_length=200, verbose_name='görev notu')),
                ('is_ai_suggested', models.BooleanField(default=False, verbose_name='AI önerisi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='hr.employee', verbose_name='personel')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr.shift', verbose_name='vardiya')),
            ],
            options={
                'verbose_name': 'Vardiya ataması',
                'verbose_name_plural': 'Vardiya atamaları',
                'ordering': ['work_date', 'shift__start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('check_in', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='giriş')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='çıkış')),
                ('break_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='mola (dk)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='not')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee', verbose_name='personel')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='hr.shiftassignment', verbose_name='vardiya ataması')),
            ],
            options={
                'verbose_name': 'Puantaj kaydı',
                'verbose_name_plural': 'Puantaj kayıtları',
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('title', models.CharField(max_length=200, verbose_name='başlık')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('target_roles', models.JSONField(blank=True, default=list, verbose_name='hedef roller')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='son tarih')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('in_progress', 'Devam ediyor'), ('done', 'Tamamlandı'), ('skipped', 'Atlandı')], default='open', max_length=12, verbose_name='durum')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Düşük'), (2, 'Normal'), (3, 'Yüksek')], default=2, verbose_name='öncelik')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='tekrarlayan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='tamamlanma')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='atanan')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='tamamlayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('period_start', models.DateField(verbose_name='dönem başı')),
                ('period_end', models.DateField(verbose_name='dönem sonu')),
                ('orders_served', models.PositiveIntegerField(default=0, verbose_name='servis edilen sipariş')),
                ('sales_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='satış toplamı')),
                ('average_ticket', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ortalama adisyon')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='çalışılan saat')),
                ('void_count', models.PositiveIntegerField(default=0, verbose_name='iptal sayısı')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='verilen indirim')),
                ('late_count', models.PositiveIntegerField(default=0, verbose_name='geç kalma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='hr.employee', verbose_name='personel')),
            ],
            options={
                'verbose_name': 'Performans özeti',
                'verbose_name_plural': 'Performans özetleri',
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'period_start', 'period_end'), name='uniq_performance_period')],
            },
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['work_date', 'status'], name='hr_shiftass_work_da_2441d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date', 'shift'), name='uniq_shift_per_employee_day'),
        ),
    ]
