# Generated by Django 5.1.14 on 2026-08-15 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('label', models.CharField(max_length=200, verbose_name='etiket')),
                ('directory', models.CharField(max_length=500, verbose_name='yedek dizini')),
                ('files', models.JSONField(blank=True, default=list, verbose_name='yedeklenen dosyalar')),
                ('git_commit', models.CharField(blank=True, max_length=64, verbose_name='git commit')),
                ('git_branch', models.CharField(blank=True, max_length=120, verbose_name='git dalı')),
                ('is_restored', models.BooleanField(default=False, verbose_name='geri yüklendi')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='geri yükleme zamanı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Geri alma noktası',
                'verbose_name_plural': 'Geri alma noktaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('title', models.CharField(max_length=200, verbose_name='başlık')),
                ('instruction', models.TextField(verbose_name='kullanıcı talimatı')),
                ('status', models.CharField(choices=[('draft', 'Öneri hazırlandı'), ('reviewing', 'İnceleniyor'), ('approved', 'Onaylandı'), ('applied', 'Uygulandı'), ('rejected', 'Reddedildi'), ('reverted', 'Geri alındı'), ('failed', 'Uygulama başarısız')], db_index=True, default='draft', max_length=10, verbose_name='durum')),
                ('provider', models.CharField(blank=True, max_length=32, verbose_name='AI sağlayıcı')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='AI model')),
                ('explanation', models.TextField(blank=True, verbose_name='AI açıklaması')),
                ('target_files', models.JSONField(blank=True, default=list, verbose_name='hedef dosyalar')),
                ('diff', models.TextField(blank=True, verbose_name='birleşik diff')),
                ('branch_name', models.CharField(blank=True, help_text='Değişiklik doğrudan ana dala uygulanmaz.', max_length=120, verbose_name='çalışma dalı')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='onay zamanı')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='uygulama zamanı')),
                ('tests_run', models.BooleanField(default=False, verbose_name='test çalıştırıldı')),
                ('tests_passed', models.BooleanField(default=False, verbose_name='testler geçti')),
                ('test_output', models.TextField(blank=True, verbose_name='test çıktısı')),
                ('rejection_reason', models.CharField(blank=True, max_length=300, verbose_name='ret gerekçesi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_proposals', to=settings.AUTH_USER_MODEL, verbose_name='onaylayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_proposals', to=settings.AUTH_USER_MODEL, verbose_name='talep eden')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='devcenter.snapshot', verbose_name='geri alma noktası')),
            ],
            options={
                'verbose_name': 'Kod önerisi',
                'verbose_name_plural': 'Kod önerileri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('command', models.CharField(max_length=1000, verbose_name='komut')),
                ('working_directory', models.CharField(max_length=500, verbose_name='çalışma dizini')),
                ('status', models.CharField(choices=[('pending', 'Onay bekliyor'), ('running', 'Çalışıyor'), ('success', 'Başarılı'), ('failed', 'Başarısız'), ('timeout', 'Zaman aşımı'), ('blocked', 'Engellendi'), ('rejected', 'Kullanıcı reddetti')], db_index=True, default='pending', max_length=10, verbose_name='durum')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='çıkış kodu')),
                ('stdout', models.TextField(blank=True, verbose_name='standart çıktı')),
                ('stderr', models.TextField(blank=True, verbose_name='hata çıktısı')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='süre (ms)')),
                ('block_reason', models.CharField(blank=True, max_length=300, verbose_name='engelleme nedeni')),
                ('required_confirmation', models.BooleanField(default=False, verbose_name='onay gerektirdi')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='onay zamanı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_runs', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
            options={
                'verbose_name': 'Terminal komutu',
                'verbose_name_plural': 'Terminal komutları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='devcenter_c_created_2b5150_idx')],
            },
        ),
    ]
