# Generated by Django 5.1.14 on 2026-08-15 02:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('title', models.CharField(default='Yeni sohbet', max_length=200, verbose_name='başlık')),
                ('task', models.CharField(choices=[('general', 'Genel asistan'), ('reasoning', 'Muhakeme ve raporlama'), ('code', 'Kod yardımcısı'), ('math', 'Maliyet / sayısal analiz'), ('vision', 'Görsel analiz'), ('domain', 'Alan bilgisi (alerjen vb.)'), ('embedding', 'Vektör gömme')], default='general', max_length=16, verbose_name='görev')),
                ('provider_preference', models.CharField(blank=True, max_length=32, verbose_name='tercih edilen sağlayıcı')),
                ('model_preference', models.CharField(blank=True, max_length=120, verbose_name='tercih edilen model')),
                ('is_archived', models.BooleanField(default=False, verbose_name='arşivlendi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
            options={
                'verbose_name': 'AI sohbeti',
                'verbose_name_plural': 'AI sohbetleri',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Kullanıcı'), ('assistant', 'Asistan'), ('system', 'Sistem')], max_length=12, verbose_name='rol')),
                ('content', models.TextField(verbose_name='içerik')),
                ('provider', models.CharField(blank=True, max_length=32, verbose_name='sağlayıcı')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='model')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='zaman')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation', verbose_name='sohbet')),
            ],
            options={
                'verbose_name': 'AI mesajı',
                'verbose_name_plural': 'AI mesajları',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('kind', models.CharField(choices=[('daily_summary', 'Günlük yönetici özeti'), ('demand_forecast', 'Talep tahmini'), ('menu_engineering', 'Menü mühendisliği'), ('waste_analysis', 'İsraf analizi'), ('staff_suggestion', 'Personel önerisi'), ('price_simulation', 'Fiyat simülasyonu'), ('anomaly', 'Anormallik tespiti'), ('churn', 'Müşteri kaybı riski'), ('sentiment', 'Yorum duygu analizi'), ('campaign', 'Kampanya önerisi'), ('stock_forecast', 'Stok tükenme tahmini')], db_index=True, max_length=20, verbose_name='tür')),
                ('title', models.CharField(max_length=200, verbose_name='başlık')),
                ('summary', models.TextField(verbose_name='özet')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='detaylar')),
                ('confidence', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=8, verbose_name='güven düzeyi')),
                ('data_points', models.PositiveIntegerField(default=0, help_text='Analizin dayandığı kayıt sayısı. Az veri = düşük güven.', verbose_name='veri noktası sayısı')),
                ('limitations', models.TextField(blank=True, help_text='Bu tahminin neden kesin olmadığını açıklar.', verbose_name='sınırlamalar')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='dönem başı')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='dönem sonu')),
                ('generated_by_ai', models.BooleanField(default=True, verbose_name='AI tarafından üretildi')),
                ('provider', models.CharField(blank=True, max_length=32, verbose_name='sağlayıcı')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='model')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='okundu / işlendi')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_insights', to=settings.AUTH_USER_MODEL, verbose_name='işleyen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'AI içgörüsü',
                'verbose_name_plural': 'AI içgörüleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='ai_aiinsigh_kind_edf0e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('task', models.CharField(choices=[('general', 'Genel asistan'), ('reasoning', 'Muhakeme ve raporlama'), ('code', 'Kod yardımcısı'), ('math', 'Maliyet / sayısal analiz'), ('vision', 'Görsel analiz'), ('domain', 'Alan bilgisi (alerjen vb.)'), ('embedding', 'Vektör gömme')], db_index=True, default='general', max_length=16, verbose_name='görev')),
                ('feature', models.CharField(blank=True, db_index=True, help_text="Hangi ekran/işlev çağırdı (ör. 'menu_description').", max_length=60, verbose_name='özellik')),
                ('provider', models.CharField(db_index=True, max_length=32, verbose_name='sağlayıcı')),
                ('model', models.CharField(max_length=120, verbose_name='model')),
                ('is_local', models.BooleanField(default=True, verbose_name='yerel model')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='girdi token')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='çıktı token')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12, verbose_name='tahminî maliyet (USD)')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='gecikme (ms)')),
                ('outcome', models.CharField(choices=[('success', 'Başarılı'), ('failed', 'Başarısız'), ('timeout', 'Zaman aşımı'), ('blocked_budget', 'Bütçe limiti'), ('blocked_policy', 'Politika engeli'), ('fallback', 'Yedek sağlayıcıya düşüldü')], db_index=True, default='success', max_length=16, verbose_name='sonuç')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='hata')),
                ('prompt_preview', models.TextField(blank=True, help_text='Maskelenmiş, kısaltılmış istem.', verbose_name='istem önizleme')),
                ('response_preview', models.TextField(blank=True, verbose_name='yanıt önizleme')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
            options={
                'verbose_name': 'AI kullanım kaydı',
                'verbose_name_plural': 'AI kullanım kayıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'provider'], name='ai_aiusagel_created_1442d6_idx'), models.Index(fields=['feature', '-created_at'], name='ai_aiusagel_feature_c981db_idx')],
            },
        ),
    ]
