# Generated by Django 5.1.14 on 2026-08-15 02:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ad')),
                ('is_fixed', models.BooleanField(default=False, help_text='Kira, maaş gibi düzenli giderler.', verbose_name='sabit gider')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='sıra')),
            ],
            options={
                'verbose_name': 'Gider kategorisi',
                'verbose_name_plural': 'Gider kategorileri',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('closing_date', models.DateField(db_index=True, unique=True, verbose_name='tarih')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='sipariş sayısı')),
                ('guest_count', models.PositiveIntegerField(default=0, verbose_name='misafir sayısı')),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='brüt satış')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='indirim')),
                ('refund_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='iade')),
                ('service_charge_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='servis bedeli')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='KDV')),
                ('net_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='net satış')),
                ('tip_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='bahşiş')),
                ('payment_breakdown', models.JSONField(blank=True, default=dict, verbose_name='ödeme dağılımı')),
                ('category_breakdown', models.JSONField(blank=True, default=dict, verbose_name='kategori dağılımı')),
                ('cash_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='beklenen nakit')),
                ('cash_counted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='sayılan nakit')),
                ('void_count', models.PositiveIntegerField(default=0, verbose_name='iptal sayısı')),
                ('void_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='iptal tutarı')),
                ('notes', models.TextField(blank=True, verbose_name='notlar')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI günlük özeti')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings', to='orders.cashsession', verbose_name='kasa oturumu')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_closings', to=settings.AUTH_USER_MODEL, verbose_name='kapatan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Gün sonu kapanışı',
                'verbose_name_plural': 'Gün sonu kapanışları',
                'ordering': ['-closing_date'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=160, verbose_name='ad')),
                ('report_type', models.CharField(max_length=60, verbose_name='rapor türü')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filtreler')),
                ('is_shared', models.BooleanField(default=False, verbose_name='paylaşılan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='sahip')),
            ],
            options={
                'verbose_name': 'Kayıtlı rapor',
                'verbose_name_plural': 'Kayıtlı raporlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('description', models.CharField(max_length=300, verbose_name='açıklama')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='tutar')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='KDV')),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='tarih')),
                ('payment_method', models.CharField(choices=[('cash', 'Nakit'), ('bank', 'Banka'), ('card', 'Kart'), ('credit', 'Vadeli')], default='cash', max_length=10, verbose_name='ödeme yöntemi')),
                ('invoice_number', models.CharField(blank=True, max_length=60, verbose_name='belge no')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='fiş görseli')),
                ('ai_extracted_data', models.JSONField(blank=True, default=dict, help_text='Fiş görselinden yapay zekâ ile okunan alanlar.', verbose_name='AI çıkarımı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='kaydeden')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.supplier', verbose_name='tedarikçi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='reports.expensecategory', verbose_name='kategori')),
            ],
            options={
                'verbose_name': 'Gider',
                'verbose_name_plural': 'Giderler',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['-expense_date', 'category'], name='reports_exp_expense_122103_idx')],
            },
        ),
    ]
