# Generated by Django 5.1.14 on 2026-08-15 02:26

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='kod')),
                ('name', models.CharField(max_length=100, verbose_name='ad')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='ikon')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='açıklama')),
            ],
            options={
                'verbose_name': 'Alerjen',
                'verbose_name_plural': 'Alerjenler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=80, verbose_name='ad')),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ürün fiyatına eklenecek tutar (negatif olabilir).', max_digits=10, verbose_name='fiyat farkı')),
                ('recipe_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Stok düşerken reçete miktarları bu katsayıyla çarpılır.', max_digits=6, verbose_name='reçete katsayısı')),
                ('is_default', models.BooleanField(default=False, verbose_name='varsayılan')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='sıra')),
            ],
            options={
                'verbose_name': 'Porsiyon',
                'verbose_name_plural': 'Porsiyonlar',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('yield_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Bu reçete kaç porsiyon üretir?', max_digits=8, verbose_name='verim (porsiyon)')),
                ('preparation_notes', models.TextField(blank=True, verbose_name='hazırlık notları')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='işçilik maliyeti')),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='genel gider payı')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'Reçete',
                'verbose_name_plural': 'Reçeteler',
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='miktar')),
                ('waste_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hazırlık sırasındaki kayıp (soyma, temizleme vb.).', max_digits=5, verbose_name='fire oranı (%)')),
                ('is_optional', models.BooleanField(default=False, verbose_name='isteğe bağlı')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='not')),
            ],
            options={
                'verbose_name': 'Reçete malzemesi',
                'verbose_name_plural': 'Reçete malzemeleri',
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=120, verbose_name='ad')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='kısa ad')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='açıklama')),
                ('color', models.CharField(default='#0d6efd', help_text='POS ekranındaki kategori rengi (#RRGGBB).', max_length=7, verbose_name='renk')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='ikon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='görsel')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='sıra')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='üst kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=120, verbose_name='ad')),
                ('start_time', models.TimeField(default=datetime.time(0, 0), verbose_name='başlangıç saati')),
                ('end_time', models.TimeField(default=datetime.time(23, 59), verbose_name='bitiş saati')),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='Boş = her gün. Örnek: [0,1,2,3,4]', verbose_name='günler')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('categories', models.ManyToManyField(blank=True, related_name='schedules', to='catalog.category', verbose_name='kategoriler')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Menü zaman planı',
                'verbose_name_plural': 'Menü zaman planları',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=120, verbose_name='ad')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('min_select', models.PositiveSmallIntegerField(default=0, verbose_name='en az seçim')),
                ('max_select', models.PositiveSmallIntegerField(default=1, help_text='0 = sınırsız', verbose_name='en çok seçim')),
                ('is_required', models.BooleanField(default=False, verbose_name='zorunlu')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='sıra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Seçenek grubu',
                'verbose_name_plural': 'Seçenek grupları',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=120, verbose_name='ad')),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='fiyat farkı')),
                ('ingredient_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='malzeme miktarı')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='sıra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('ingredient', models.ForeignKey(blank=True, help_text='Seçildiğinde stoktan düşülecek malzeme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiers', to='inventory.ingredient', verbose_name='bağlı malzeme')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.modifiergroup', verbose_name='grup')),
            ],
            options={
                'verbose_name': 'Seçenek',
                'verbose_name_plural': 'Seçenekler',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='eski fiyat')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='yeni fiyat')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='değişim zamanı')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='gerekçe')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='değiştiren')),
            ],
            options={
                'verbose_name': 'Fiyat geçmişi',
                'verbose_name_plural': 'Fiyat geçmişi',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(db_index=True, max_length=160, verbose_name='ad')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='kısa ad')),
                ('sku', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='stok kodu')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='barkod')),
                ('kind', models.CharField(choices=[('food', 'Yemek'), ('drink', 'İçecek'), ('alcohol', 'Alkollü içecek'), ('dessert', 'Tatlı'), ('combo', 'Menü / kombinasyon'), ('other', 'Diğer')], default='food', max_length=10, verbose_name='tür')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('ai_description', models.TextField(blank=True, help_text='Yapay zekâ tarafından önerilen açıklama; onaylanıp kullanılabilir.', verbose_name='AI menü açıklaması')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='görsel')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='satış fiyatı (KDV dahil)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='KDV oranı (%)')),
                ('preparation_minutes', models.PositiveIntegerField(default=10, verbose_name='hazırlık süresi (dk)')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='kalori (kcal)')),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='protein (g)')),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='karbonhidrat (g)')),
                ('fat_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='yağ (g)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktif')),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Stok tükendiğinde otomatik olarak kapatılabilir.', verbose_name='satışa açık')),
                ('auto_disable_on_stockout', models.BooleanField(default=True, verbose_name='stok bitince otomatik kapat')),
                ('unavailable_reason', models.CharField(blank=True, max_length=200, verbose_name='kapatılma nedeni')),
                ('is_featured', models.BooleanField(default=False, verbose_name='öne çıkan')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='sıra')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='POS rengi')),
                ('allergens', models.ManyToManyField(blank=True, related_name='products', to='catalog.allergen', verbose_name='alerjenler')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='kategori')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
    ]
