# Generated by Django 5.1.14 on 2026-08-15 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('kitchen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='kitchen.station', verbose_name='hazırlık istasyonu'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product', verbose_name='ürün'),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='modifier_groups', to='catalog.product', verbose_name='ürünler'),
        ),
        migrations.AddField(
            model_name='menuschedule',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='catalog.product', verbose_name='ürünler'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='ürün'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='catalog.product', verbose_name='ürün'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='inventory.ingredient', verbose_name='malzeme'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.recipe', verbose_name='reçete'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='inventory.unitofmeasure', verbose_name='birim'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'sort_order'], name='catalog_cat_is_acti_100145_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_available'], name='catalog_pro_is_acti_f6baa6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'sort_order'], name='catalog_pro_categor_7be1da_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='uniq_variant_per_product'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='uniq_ingredient_per_recipe'),
        ),
    ]
